### PR TITLE
Enhance navbar when scrolling

### LINKED ISSUE #69: [FEATURE] Fixed Navbar on the top for Better User Experience
### Description
I want make the Navbar show in the top when the user Scroll up a bit or 1px, and it will hide when user Scroll down.

### To Reproduce
1. I will use fixed position to make Navbar in the top.
2. I will use a state for handle when user is Scroll or not, based on that state we set the fixed position.

### Additional context
Sir @mittal-parth can you assign this issue to me Sir? I am new to open source contributions and I would love to contribute to your project Sir. I also participated in Hacktoberfest2024.

### PR DESCRIPTION
**Pull request by A-4-Atom**
closes #69 
Navbar is initially hidden but when use scrolls upward it becomes visible again, so that user doesn't have to scroll all the way up.

This looks good enough to me, let me know if any changes are required.
@mittal-parth

### CODE REVIEW

**Comment by mittal-parth** [comment]
Hey @A-4-Atom!

The functionality looks good.

However, I think you have centered the elements now.

PR:
image


Original (main branch):

image

File: src/App.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const App = () => {
               </div>
             </div>
 
-            <div className={`bg-primary ${styles.flexStart}`}>
+            <div className={`bg-primary ${styles.flexStart} pt-[80px]`}>
```
Comment (mittal-parth) [inline src/App.jsx:47]: Curious, why do we need this?

Comment (A-4-Atom) [reply src/App.jsx:47]: the navbar has **position: fixed;** now it no longer takes space in the layout, so we have to manually add padding to the element below it otherwise it appears behind the navbar.

image

**Comment by A-4-Atom** [comment]
The navbar appeared centered in my browser so that's why i centered element. Anyways I've updated the styles.
@mittal-parth 

https://github.com/user-attachments/assets/1f6cfc4f-65ae-4789-bced-98afc0582a34

**Comment by mittal-parth** [comment]
You are the best, thanks again @A-4-Atom!
