### PR TITLE
Fix carousel on mobile devices #56

### LINKED ISSUE #56: Achievements: Fix carousel on mobile devices
The arrows scroll the cards more than the phone width making it difficult to read. 

The arrows should scroll correctly on mobile (one card at a time) and bigger devices (2/3 cards at a time).

### PR DESCRIPTION
**Pull request by Sapna127**
Fix for the issue of carousel scroll on mobile devices..  

Closes #56

### CODE REVIEW

File: src/components/Achievements.jsx [hunk 1]
```diff
@@ -92,75 +96,37 @@ const Achievements = () => {
...
-          <a
-            className=" inline-flex items-center hover:text-teal-200"
-            href={props.project}
-            target="_blank"
-            rel="noopener noreferrer"
-          >
+          <a className=" inline-flex items-center hover:text-teal-200" href={props.project} target="_blank" rel="noopener noreferrer">
             <BsLink45Deg size="1.5rem" className="inline" />
           </a>
         )}
```
Comment (mittal-parth) [inline src/components/Achievements.jsx:132]: Can you revert the linter here?

**Review by mittal-parth — CHANGES_REQUESTED** [review]
Thanks, looks great, left a small comment!

File: src/components/Achievements.jsx (hunk 1 above)
Comment (mittal-parth) [reply src/components/Achievements.jsx]: Well, you dont have to revert the commit. You can always make a new commit for the changes.

And making a new branch is not required, rather discouraged because often there are multiple rounds of reviews on the same PR. We can't then keep making new branches right? :) 
So its better to keep the discussion in one place.

And I squash the commits before merging, so commits will be clean. However, this might depend on the project. Regardless, having multiple commits is never an issue.

**Comment by mittal-parth** [comment]
Merged, thanks @Sapna127! 🚀

File: src/components/Achievements.jsx (hunk 1 above)
Comment (Sapna127) [reply src/components/Achievements.jsx]: got it. Thanks for explaining it to me :)
